export type FormState = {
    ldl?: string,
    hdl?: string,
    hasDiabetes: boolean | null,
    birthDate: Date,
    height: string,
    weight: string,
    isMan: boolean | null,
    isSmoker: boolean | null,
    bloodPressure: string,
    bloodPressureTreated: boolean | null,
    waistCircumference: string,
    practiceExercise: boolean | null,
    eatVegetablesEveryDay: boolean | null,
    highGlucose: boolean | null,
    familyWithDiabetes: number | null,
    isAlcoholic: boolean | null,
    familyWithObesity: boolean | null,
    grauDispneia: number,
    sumDPOC: number,
    sumAsma: number,
    crisesDPOC: number,
    sumChronicPain: number,
}

export type FormStateError = {
    birthDateError: string
    heightError: string,
    isManError: boolean,
    bloodPressureError: string,
    bloodPressureTreatedError: boolean,
    isSmokerError: boolean,
    weightError: string,
    diabetesError: boolean,
    waistCircumferenceError: string,
    practiceExerciseError: boolean,
    eatVegetablesEveryDayError: boolean,
    highGlucoseError: boolean,
    familyWithDiabetesError: boolean,
    familyWithObesityError: boolean,
    isAlcoholicError: boolean,
}